"""
certify.py — the automated WCET annotation + certification pass (§2.5).

Four sequential operations:
  1. CFG extraction (wcet_ipet.extract_cfg)
  2. Instruction attribution + ILP construction/solution (wcet_ipet.analyze)
  3. Annotation emission: `// @wcet_bound: X cycles` inserted into the C11
  4. Lean4 proof-obligation stub generation + certificate.json bundle write

Also computes clock-cycle -> latency conversion and the deadline margin
against a configurable real-time deadline (default 50 ms, §1.1/§3.3).
"""
from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path

from src.wcet_ipet import analyze

CLOCK_HZ = 168_000_000
DEADLINE_S = 0.050  # 50 ms neurostimulation deadline

LEAN4_STUB_TEMPLATE = '''\
-- Auto-generated by certify.py. Specification, NOT a discharged proof.
-- theorem states the IPET-derived WCET bound as a proof obligation
-- against the compiled inference function `{fn_name}`.
-- `sorry` marks this obligation as OPEN.

import Mathlib.Tactic

/-- Cycle-count semantics of the compiled function under the ARM
    Cortex-M4F instruction timing model used in the IPET analysis. -/
axiom wcet_cycles : (Unit -> Unit) -> Nat

axiom {fn_name} : Unit -> Unit

theorem {fn_name}_wcet_bound : wcet_cycles {fn_name} <= {bound} := by
  sorry
'''


def annotate_source(c_source: str, applied_bounds: dict[str, int]) -> str:
    """Insert `// @wcet_bound: X cycles` immediately above each
    `void lif_layerN_step(...)` function header."""
    lines = c_source.splitlines()
    out = []
    fn_pattern = re.compile(r"void (lif_layer\d+)_step\(")
    for line in lines:
        match = fn_pattern.search(line)
        if match:
            name = match.group(1)
            bound = applied_bounds.get(name)
            if bound is not None:
                out.append(f"// @wcet_bound: {bound} cycles")
        out.append(line)
    return "\n".join(out)


def write_lean_stubs(applied_bounds: dict[str, int], out_dir: str) -> list[str]:
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    paths = []
    for name, bound in applied_bounds.items():
        content = LEAN4_STUB_TEMPLATE.format(fn_name=name, bound=bound)
        path = Path(out_dir) / f"{name}_wcet.lean"
        path.write_text(content)
        paths.append(str(path))
    return paths


def run(c_source_path: str, annotated_out_path: str, lean_dir: str,
        certificate_out_path: str, target: str = "x86_64-linux-gnu",
        commit: str = "89b65e0", llvm_version: str = "22.1.8",
        uniform_bound: bool = True) -> dict:
    t0 = time.time()
    c_source = Path(c_source_path).read_text()

    wcet_result = analyze(c_source, uniform_bound=uniform_bound)
    applied = wcet_result["per_layer_applied"]
    network_bound = wcet_result["network_bound_cycles"]

    annotated = annotate_source(c_source, applied)
    Path(annotated_out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(annotated_out_path).write_text(annotated)

    lean_paths = write_lean_stubs(applied, lean_dir)

    certified_latency_s = network_bound / CLOCK_HZ
    # margin > 1.0  => WCET fits inside the deadline with room to spare (SAFE)
    # margin < 1.0  => WCET exceeds the deadline (UNSAFE)
    margin = DEADLINE_S / certified_latency_s if certified_latency_s > 0 else float("inf")
    deadline_met = certified_latency_s <= DEADLINE_S

    elapsed = time.time() - t0

    certificate = {
        "pipeline_version": "0.1.0",
        "target": target,
        "snn_mlir_commit": commit,
        "llvm_version": llvm_version,
        "clock_hz": CLOCK_HZ,
        "deadline_s": DEADLINE_S,
        "wcet": {
            "per_layer_raw_cycles": wcet_result["per_layer_raw"],
            "per_layer_applied_cycles": applied,
            "uniform_bound_policy": uniform_bound,
            "certified_network_bound_cycles": network_bound,
            "certified_network_latency_s": certified_latency_s,
            "deadline_margin_x": margin,
            "deadline_met": deadline_met,
        },
        "artifacts": {
            "annotated_c11": annotated_out_path,
            "lean4_stubs": lean_paths,
        },
        "pipeline_runtime_s": elapsed,
        "notes": [
            "Lean4 stubs are specifications (sorry-terminated), not "
            "discharged proofs.",
            "Compilation target may differ from the ARM Cortex-M4F timing "
            "model used for WCET; see README cross-architecture caveat.",
        ],
    }

    Path(certificate_out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(certificate_out_path).write_text(json.dumps(certificate, indent=2))
    print(json.dumps(certificate, indent=2))
    return certificate


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--c-source", default="artifacts/build/main.c")
    ap.add_argument("--annotated-out", default="artifacts/build/main.annotated.c")
    ap.add_argument("--lean-dir", default="lean_stubs")
    ap.add_argument("--certificate-out", default="artifacts/certificate.json")
    ap.add_argument("--target", default="x86_64-linux-gnu")
    ap.add_argument("--per-layer", action="store_true",
                     help="Use tighter individualized per-layer bounds "
                          "instead of the uniform conservative policy.")
    args = ap.parse_args()
    run(args.c_source, args.annotated_out, args.lean_dir, args.certificate_out,
        target=args.target, uniform_bound=not args.per_layer)


if __name__ == "__main__":
    main()
