"""
NIR graph -> C11 source (§2.3).

Tries the real `snn-mlir` compiler binary on PATH first (with the flags
described in the paper). If it isn't available, falls back to a built-in
code generator that emits C11 in the same shape: CUBA-LIF layers with two
persistent state buffers each, and a `_mlir_ciface_snn_forward_step` entry
point, so the rest of the pipeline (WCET analysis, annotation, Lean4 stub
generation) has real source to operate on.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

GCC_FLAGS = ["-O0", "-shared", "-fPIC", "-mfpu=fpv4-sp-d16", "-mfloat-abi=hard"]


def compile_nir(nir_path: str, out_c_path: str, target: str = "x86_64-linux-gnu") -> dict:
    binary = shutil.which("snn-mlir")
    if binary:
        return _compile_with_snn_mlir(binary, nir_path, out_c_path, target)
    return _fallback_codegen(nir_path, out_c_path, target)


def _compile_with_snn_mlir(binary: str, nir_path: str, out_c_path: str, target: str) -> dict:
    Path(out_c_path).parent.mkdir(parents=True, exist_ok=True)
    cmd = [binary, "--input", nir_path, "--emit=c11", "--target", target,
           "-o", out_c_path]
    subprocess.run(cmd, check=True)
    return {"backend": "snn-mlir", "target": target, "path": out_c_path}


def _fallback_codegen(nir_path: str, out_c_path: str, target: str) -> dict:
    graph = json.loads(Path(nir_path).read_text())
    lif_nodes = [n for n in graph["nodes"] if n["type"] == "LIFLayer"]
    affine_nodes = {n["id"]: n for n in graph["nodes"] if n["type"] == "Affine"}

    edges = graph["edges"]

    def upstream_affine(lif_id: str):
        for a, b in edges:
            if b == lif_id and a in affine_nodes:
                return affine_nodes[a]
        return None

    c_lines = [
        f"// Auto-generated by compile_snn_mlir.py fallback codegen",
        f"// @target: {target}",
        f"#include <string.h>",
        "",
        "typedef struct { float *v; float *out; } LIFState;",
        "",
    ]

    for i, lif in enumerate(lif_nodes, start=1):
        affine = upstream_affine(lif["id"])
        n_in = affine["in_features"] if affine else 0
        n_out = affine["out_features"] if affine else 0
        beta = lif["beta"]
        theta = lif["threshold"]
        fn_name = f"lif_layer{i}"
        c_lines += [
            f"// LIF layer {i}: in={n_in} out={n_out} beta={beta} theta={theta}",
            f"// CUBA-LIF: persistent state buffers `v_{fn_name}` (membrane) "
            f"and `s_{fn_name}` (spike out)",
            f"static float v_{fn_name}[{n_out}];",
            f"static float s_{fn_name}[{n_out}];",
            "",
            f"void {fn_name}_step(const float *in, const float *weight, float *out) {{",
            f"    for (int i = 0; i < {n_out}; i++) {{",
            f"        float acc = {beta}f * v_{fn_name}[i];",
            f"        for (int j = 0; j < {n_in}; j++) {{",
            f"            acc += weight[i * {n_in} + j] * in[j];",
            f"        }}",
            f"        int spike = acc >= {theta}f;",
            f"        out[i] = (float) spike;",
            f"        v_{fn_name}[i] = acc * (1.0f - (float) spike);",
            f"    }}",
            f"}}",
            "",
        ]

    step_signature = "void _mlir_ciface_snn_forward_step(const float *input, float *output)"
    body = [f"    static float buf1[{lif_nodes[0]['threshold'] and 0 or 0}];"]  # placeholder unused
    c_lines += [
        step_signature + " {",
        "    // Sequentially invoke each compiled LIF layer step function.",
        "    // Buffer sizes are fixed at compile time from the NIR graph.",
    ]
    prev = "input"
    buf_names = []
    for i, lif in enumerate(lif_nodes, start=1):
        affine = upstream_affine(lif["id"])
        n_out = affine["out_features"] if affine else 0
        buf = f"buf{i}"
        buf_names.append((buf, n_out))
        target_buf = "output" if i == len(lif_nodes) else buf
        if i < len(lif_nodes):
            c_lines.append(f"    static float {buf}[{n_out}];")

    c_lines_body = []
    for i, lif in enumerate(lif_nodes, start=1):
        affine = upstream_affine(lif["id"])
        n_in = affine["in_features"] if affine else 0
        n_out = affine["out_features"] if affine else 0
        src_buf = "input" if i == 1 else f"buf{i-1}"
        dst_buf = "output" if i == len(lif_nodes) else f"buf{i}"
        c_lines_body.append(
            f"    lif_layer{i}_step({src_buf}, weight_layer{i}, {dst_buf});"
        )
    c_lines += c_lines_body
    c_lines.append("}")
    c_lines.append("")

    # weight arrays (extern declarations; values would be linked from a
    # separate weights.c in a full build — omitted here since WCET analysis
    # only needs control-flow structure, not weight values)
    weight_decls = []
    for i, lif in enumerate(lif_nodes, start=1):
        affine = upstream_affine(lif["id"])
        n_in = affine["in_features"] if affine else 0
        n_out = affine["out_features"] if affine else 0
        weight_decls.append(f"extern float weight_layer{i}[{n_out} * {n_in}];")
    c_lines = weight_decls + [""] + c_lines

    Path(out_c_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_c_path).write_text("\n".join(c_lines))

    return {"backend": "fallback-codegen", "target": target, "path": out_c_path,
            "n_lif_layers": len(lif_nodes)}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--nir", default="artifacts/build/seizure_snn.nir.json")
    ap.add_argument("--out", default="artifacts/build/main.c")
    ap.add_argument("--target", default="x86_64-linux-gnu")
    args = ap.parse_args()
    result = compile_nir(args.nir, args.out, args.target)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
